### ISSUE TITLE
SPS Halloween Welcome Reception

### ISSUE THREAD

**Issue by jaylenw** [jaylenw/APS_2015_Far_West_CSULB_Website#4]
Halloween welcome reception (SPS Chapter)
Thursday, Oct. 29th, 6:30pm

Details must be added

**Comment by HavenAbove** [comment]
Hi Jaylen,

I just signed up for github when we started this project, so I'm not sure I
know exactly what to do? I see the task emails you sent me, but I suppose
I'll need access to the website to do this? Or a local site right? Do I
have access to the local site yet?

On Thu, Jul 9, 2015 at 11:24 PM, Jaylen Wimbish notifications@github.com
wrote:

> Assigned #4
> https://github.com/jaylenw/APS_2015_Far_West_CSULB_Website/issues/4 to
> @HavenAbove https://github.com/HavenAbove.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jaylenw/APS_2015_Far_West_CSULB_Website/issues/4#event-352611203
> .

## 

Thanks,
Samuel Pottish

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.

**Comment by jaylenw** [comment]
Hey Sam,

For now you should be able to work on the files locally.  The files on
Github were pulled from the school's servers.   If you visit the site you
will see instructions to run the development server.  Let me know if you
are able to do that.
If you have a Mac or linux machine it should be simple.  If you need any
help let me know.   You will then have full access to modify the files
locally and see the changes locally as well.  When we both determine we are
done we can copy the files to Terry.

First try and do what is listed on the readme
https://github.com/jaylenw/APS_2015_Far_West_CSULB_Website.  Everything
else then should be easy.  You could also download the github client to
make things easier for you (for mac) https://mac.github.com/.  There is one
also for windows.

Essentially with github when u make a change to a file and save it you add
it to the version control system.  You then "commit it" by saying what you
have changed.  Then you push back to the repository on the server.

Thanks Sam.

On Mon, Jul 13, 2015 at 7:25 PM, HavenAbove notifications@github.com
wrote:

> Hi Jaylen,
> 
> I just signed up for github when we started this project, so I'm not sure I
> know exactly what to do? I see the task emails you sent me, but I suppose
> I'll need access to the website to do this? Or a local site right? Do I
> have access to the local site yet?
> 
> On Thu, Jul 9, 2015 at 11:24 PM, Jaylen Wimbish notifications@github.com
> wrote:
> 
> > Assigned #4
> > https://github.com/jaylenw/APS_2015_Far_West_CSULB_Website/issues/4 to
> > @HavenAbove https://github.com/HavenAbove.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/jaylenw/APS_2015_Far_West_CSULB_Website/issues/4#event-352611203
> > 
> > .
> 
> ## 
> 
> Thanks,
> Samuel Pottish
> 
> This email and any files transmitted with it are confidential and intended
> solely for the use of the individual or entity to whom they are addressed.
> If you have received this email in error please notify the system manager.
> This message contains confidential information and is intended only for the
> individual named. If you are not the named addressee you should not
> disseminate, distribute or copy this e-mail. Please notify the sender
> immediately by e-mail if you have received this e-mail by mistake and
> delete this e-mail from your system. If you are not the intended recipient
> you are notified that disclosing, copying, distributing or taking any
> action in reliance on the contents of this information is strictly
> prohibited.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jaylenw/APS_2015_Far_West_CSULB_Website/issues/4#issuecomment-121114319
> .

## 
- Jaylen Wimbish
  http://jaylenwimbish.com

**Comment by HavenAbove** [comment]
When I look at this page locally I get a syntax error in Dreamweaver. I'm
trying to fix this, but the index.html code is not working.

On Mon, Jul 13, 2015 at 7:44 PM, Jaylen Wimbish notifications@github.com
wrote:

> Hey Sam,
> 
> For now you should be able to work on the files locally. The files on
> Github were pulled from the school's servers. If you visit the site you
> will see instructions to run the development server. Let me know if you
> are able to do that.
> If you have a Mac or linux machine it should be simple. If you need any
> help let me know. You will then have full access to modify the files
> locally and see the changes locally as well. When we both determine we are
> done we can copy the files to Terry.
> 
> First try and do what is listed on the readme
> https://github.com/jaylenw/APS_2015_Far_West_CSULB_Website. Everything
> else then should be easy. You could also download the github client to
> make things easier for you (for mac) https://mac.github.com/. There is one
> also for windows.
> 
> Essentially with github when u make a change to a file and save it you add
> it to the version control system. You then "commit it" by saying what you
> have changed. Then you push back to the repository on the server.
> 
> Thanks Sam.
> 
> On Mon, Jul 13, 2015 at 7:25 PM, HavenAbove notifications@github.com
> wrote:
> 
> > Hi Jaylen,
> > 
> > I just signed up for github when we started this project, so I'm not
> > sure I
> > know exactly what to do? I see the task emails you sent me, but I suppose
> > I'll need access to the website to do this? Or a local site right? Do I
> > have access to the local site yet?
> > 
> > On Thu, Jul 9, 2015 at 11:24 PM, Jaylen Wimbish <
> > notifications@github.com>
> > wrote:
> > 
> > > Assigned #4
> > > https://github.com/jaylenw/APS_2015_Far_West_CSULB_Website/issues/4
> > > to
> > > @HavenAbove https://github.com/HavenAbove.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/jaylenw/APS_2015_Far_West_CSULB_Website/issues/4#event-352611203
> > 
> > > .
> > 
> > ## 
> > 
> > Thanks,
> > Samuel Pottish
> > 
> > This email and any files transmitted with it are confidential and
> > intended
> > solely for the use of the individual or entity to whom they are
> > addressed.
> > If you have received this email in error please notify the system
> > manager.
> > This message contains confidential information and is intended only for
> > the
> > individual named. If you are not the named addressee you should not
> > disseminate, distribute or copy this e-mail. Please notify the sender
> > immediately by e-mail if you have received this e-mail by mistake and
> > delete this e-mail from your system. If you are not the intended
> > recipient
> > you are notified that disclosing, copying, distributing or taking any
> > action in reliance on the contents of this information is strictly
> > prohibited.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/jaylenw/APS_2015_Far_West_CSULB_Website/issues/4#issuecomment-121114319
> > 
> > .
> 
> ## 
> - Jaylen Wimbish
>   http://jaylenwimbish.com
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jaylenw/APS_2015_Far_West_CSULB_Website/issues/4#issuecomment-121115870
> .

## 

Thanks,
Samuel Pottish

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.

**Comment by jaylenw** [comment]
Use your web browser.   The files are set up as if they are in a server environment.  I did this so transferring to the server will be easier for us.

Were you able to do this below?
1.  After cloning or downloading the the repository navigate to the
   APS_2015_Far_West_CSULB_Website directory with the command line.  
2.  You will see the "depts" folder if you were to enter the "ls" command.
3.  Enter "python -m SimpleHTTPServer"
   
   ```
   python -m SimpleHTTPServer
   ```
   
   Hit enter.  This starts our python development server.
4.  Navigate to your web browser and enter into the address bar "http://127.0.0.1:8000"
5.  You will now see the directory listing.  Navigate to depts > physics > APS.
6.  The page will now be rendered in the browser.

---

I hope that helps.  Let me know.  Thanks Sam.

**Comment by HavenAbove** [comment]
This is what I see and the code is locked and a lot of it commented out for
some reason. Never seen this before, can't edit it. Maybe I'm totally
missing something.

On Mon, Jul 13, 2015 at 7:44 PM, Jaylen Wimbish notifications@github.com
wrote:

> Hey Sam,
> 
> For now you should be able to work on the files locally. The files on
> Github were pulled from the school's servers. If you visit the site you
> will see instructions to run the development server. Let me know if you
> are able to do that.
> If you have a Mac or linux machine it should be simple. If you need any
> help let me know. You will then have full access to modify the files
> locally and see the changes locally as well. When we both determine we are
> done we can copy the files to Terry.
> 
> First try and do what is listed on the readme
> https://github.com/jaylenw/APS_2015_Far_West_CSULB_Website. Everything
> else then should be easy. You could also download the github client to
> make things easier for you (for mac) https://mac.github.com/. There is one
> also for windows.
> 
> Essentially with github when u make a change to a file and save it you add
> it to the version control system. You then "commit it" by saying what you
> have changed. Then you push back to the repository on the server.
> 
> Thanks Sam.
> 
> On Mon, Jul 13, 2015 at 7:25 PM, HavenAbove notifications@github.com
> wrote:
> 
> > Hi Jaylen,
> > 
> > I just signed up for github when we started this project, so I'm not
> > sure I
> > know exactly what to do? I see the task emails you sent me, but I suppose
> > I'll need access to the website to do this? Or a local site right? Do I
> > have access to the local site yet?
> > 
> > On Thu, Jul 9, 2015 at 11:24 PM, Jaylen Wimbish <
> > notifications@github.com>
> > wrote:
> > 
> > > Assigned #4
> > > https://github.com/jaylenw/APS_2015_Far_West_CSULB_Website/issues/4
> > > to
> > > @HavenAbove https://github.com/HavenAbove.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/jaylenw/APS_2015_Far_West_CSULB_Website/issues/4#event-352611203
> > 
> > > .
> > 
> > ## 
> > 
> > Thanks,
> > Samuel Pottish
> > 
> > This email and any files transmitted with it are confidential and
> > intended
> > solely for the use of the individual or entity to whom they are
> > addressed.
> > If you have received this email in error please notify the system
> > manager.
> > This message contains confidential information and is intended only for
> > the
> > individual named. If you are not the named addressee you should not
> > disseminate, distribute or copy this e-mail. Please notify the sender
> > immediately by e-mail if you have received this e-mail by mistake and
> > delete this e-mail from your system. If you are not the intended
> > recipient
> > you are notified that disclosing, copying, distributing or taking any
> > action in reliance on the contents of this information is strictly
> > prohibited.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/jaylenw/APS_2015_Far_West_CSULB_Website/issues/4#issuecomment-121114319
> > 
> > .
> 
> ## 
> - Jaylen Wimbish
>   http://jaylenwimbish.com
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jaylenw/APS_2015_Far_West_CSULB_Website/issues/4#issuecomment-121115870
> .

## 

Thanks,
Samuel Pottish

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.

**Comment by jaylenw** [comment]
Let me give you a call.

**Comment by jaylenw** [comment]
final version pushed to website.
